import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Ajit",
    lastName: "Sharma",
    username: "ajitTesting@gmail.com",
    profile_photo:
      "https://i.ibb.co/vkYHs3K/avengers.jpg",
    userHandler: "its_AjitSharma",
    password: "200",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    bio: "Network Engineer| Nature | Learning Web Dev ",
  },
  {
    _id: uuid(),
    firstName: "Bahubali",
    lastName: "Shiva",
    username: "bahubali@gmail.com",
    profile_photo:
      "https://i.ibb.co/Kjt8q6z/download.jpg",
    userHandler: "Bahubali",
    password: "100",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "https://BahubaliShiva.netlify.app/",
    bio: "Nature enthusiast | Mountain Climber ",
  },
  {
    _id: uuid(),
    firstName: "Ironman",
    lastName: "Ultra Pro",
    username: "ironman@gmail.com",
    profile_photo:
      "https://i.ibb.co/ypSXznn/Iron-man.jpg",
    userHandler: "IronMan",
    password: "100",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "",
    bio: "Tin Master | High Speed | Arabpati",
  },
  {
    _id: uuid(),
    firstName: "Thanos",
    lastName: "Destroyer",
    username: "thanos@gmail.com",
    profile_photo:
      "https://i.ibb.co/ZHP4VpF/Infinity-War.jpg",
    userHandler: "ThanosDestroyer",
    password: "100",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "",
    bio: "The Destruction Master | I Hate Ironman",
  },
  {
    _id: uuid(),
    firstName: "Rocky",
    lastName: "Bhai",
    username: "rockybhai@gmail.com",
    profile_photo:
      "https://i.ibb.co/7SBy3k6/download.jpg",
    userHandler: "RockyBhai",
    password: "100",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "",
    bio: "Bombay Shooter | Gold Lover | Rocking Man",
  },
  {
    _id: uuid(),
    firstName: "Pro Video",
    lastName: "Editor",
    username: "videoeditor@gmail.com",
    profile_photo:
      "https://i.ibb.co/gjjXBRd/istockphoto-944137558-170667a.jpg",
    userHandler: "VideoEditor",
    password: "100",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "",
    bio: "I can edit and fix your futures, trust me",
  },
  {
    _id: uuid(),
    firstName: "Stark",
    lastName: "Industry",
    username: "starkindustry@gmail.com",
    profile_photo:
      "https://i.ibb.co/SxVHf1N/istockphoto-183322339-612x612.jpg",
    userHandler: "StarkIndustry",
    password: "abc123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "",
    bio: "We manufacture arms, heads and legs and NASA export it",
  },
  {
    _id: uuid(),
    firstName: "Cyber",
    lastName: "Branch",
    username: "cyberbranch@gmail.com",
    profile_photo:
      "https://i.ibb.co/kXbMgp1/Fingerprint-Computer-Technology-Cyber-Security.jpg",
    userHandler: "CyberBranch",
    password: "pass123",
    createdAt: formatDate(),
    updatedAt: formatDate(),
    bookmarks: [],
    followers: [],
    following: [],
    link: "",
    bio: "Protect Your Own Privacy | stay alert | We can't help you",
  },
];
